[project]
name = "lecture-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.26",
    "litellm[caching]>=1.73.7",
    "pydantic>=2.11.7",
    "weave>=0.51.54",
]
